# Generated by Django 2.0 on 2017-12-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lists', '0001_initial'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
